databases:
  - name: dance_events_db
    databaseName: dance_events
    user: dance_events_app

services:
  - type: web
    name: dance_events
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dance_events_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
